# Generated by Django 5.2.3 on 2025-09-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactsubmission",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="contactsubmission",
            name="project_type",
        ),
        migrations.AlterField(
            model_name="resume",
            name="resume_file",
            field=models.FileField(
                help_text="Upload your latest resume in PDF format.",
                upload_to="resumes/",
            ),
        ),
    ]
