# Generated by Django 5.1.3 on 2025-10-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_contactsubmission_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=4)),
                ('end_year', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, help_text='Optional: Add details like honors, relevant coursework, etc.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order to display (e.g., 1 for first, 2 for second)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
