# Generated by Django 5.1.3 on 2025-12-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('AI', 'AI & Machine Learning'), ('IOT', 'IoT & Hardware'), ('DEV', 'Python Development')], default='DEV', max_length=3)),
                ('tech_stack', models.CharField(help_text='Comma separated tags (e.g. Python, Django, OpenCV)', max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
