# Generated by Django 5.1.3 on 2025-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Software Developer', max_length=200)),
                ('company', models.CharField(help_text='e.g. Tech Solutions Inc.', max_length=200)),
                ('location', models.CharField(default='Pune', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working here', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Short summary of your role and achievements.')),
                ('order', models.IntegerField(default=0, help_text='Higher numbers appear first')),
            ],
            options={
                'ordering': ['-order', '-start_date'],
            },
        ),
    ]
